services:
  puppet_controller:
    build:
      context: ./containers/controller
    container_name: puppet_controller
    networks:
      - puppet_lab_network
  
  test_node_01:
    build:
      context: ./containers/test_node
    container_name: test_node_01
    networks:
      - puppet_lab_network
  
  test_node_02:
    build:
      context: ./containers/test_node
    container_name: test_node_02
    networks:
      - puppet_lab_network

networks:
  puppet_lab_network:
    driver: bridge
