services:
  puppet_controller:
    build:
      context: .
      dockerfile: ./containers/controller/Dockerfile
    container_name: puppet_controller
    networks:
      - puppet_lab_network
    volumes:
      - ssh_keys:/shared
      - ./environments:/etc/puppetlabs/code/environments

  
  test_node_01:
    build:
      context: .
      dockerfile: ./containers/test_node/Dockerfile
    container_name: node_01 
    networks:
      - puppet_lab_network
    volumes:
      - ssh_keys:/shared
  
  test_node_02:
    build:
      context: .
      dockerfile: ./containers/test_node/Dockerfile
    container_name: node_02
    networks:
      - puppet_lab_network
    volumes:
      - ssh_keys:/shared

networks:
  puppet_lab_network:
    driver: bridge

volumes:
  ssh_keys:
